version: "3"

services:

    data-svc:
        restart: on-failure
        build: ./data

    user-svc:
        restart: on-failure
        build: ./user

    wsgi-svc:
        restart: on-failure
        build: ./wsgi

    nrp-svc:
        restart: on-failure
        build: ./nrp
        ports:
            - 80:80
        depends_on:
            - data-svc
            - user-svc
            - wsgi-svc
