version: "3"

services:

  auth-svc:
    restart: on-failure
    build: ./auth
    ports:
    - "8090:8080"

  data-svc:
    restart: on-failure
    build: ./data

  user-svc:
    restart: on-failure
    build: ./user

  wsgi-svc:
    restart: on-failure
    build: ./wsgi

  cadvisor-svc:
    extends:
      file: dash/docker-compose.yml
      service: cadvisor-svc

  prometheus-svc:
    extends:
      file: dash/docker-compose.yml
      service: prometheus-svc

  grafana-svc:
    extends:
      file: dash/docker-compose.yml
      service: grafana-svc

  nrp-svc:
    restart: on-failure
    build: ./nrp
    ports:
      - 80:80
    depends_on:
      - data-svc
      - user-svc
      - wsgi-svc
      - grafana-svc
      - prometheus-svc
      - cadvisor-svc
