version: "3"

services:

    data-svc:
        restart: on-failure
        build: ./data
        ports:
          - 8001:6379

    user-svc:
        restart: on-failure
        build: ./user
        ports:
          - 8002:80

    wsgi-svc:
        restart: on-failure
        build: ./wsgi
        ports:
          - 8003:80

    auth-svc:
        restart: on-failure
        build: ./auth
        ports:
          - 8004:8080

    new-nrp-svc:
        restart: on-failure
        build: ./new-nrp
        ports:
          - 8005:80
