FROM grafana/grafana
COPY datasource.yml /etc/grafana/provisioning/datasources/datasource.yml
COPY dashboard.yml /etc/grafana/provisioning/dashboards/dashboard.yml
COPY docker-monitoring_rev1.json /etc/grafana/provisioning/dashboards/docker-monitoring_rev1.json
